function t226_floating_init(el){console.log('floating_init');var wnd=$(window);var col=el.parent();el.css('max-width',el.width());el.css('width','100%');col.css('min-height',el.height());var timer;var timer_count=0;var timer_react=5;wnd.scroll(function(){if(timer){window.clearTimeout(timer);if(timer_count>=timer_react){t226_floating_scroll(el,wnd,col);timer_count=0}
timer_count++}
timer=window.setTimeout(function(){t226_floating_scroll(el,wnd,col);timer_count=0},50)});wnd.resize(function(){wnd.scroll()});wnd.scroll()}
function t226_floating_scroll(el,wnd,col){var wnd_height=wnd.height();var wnd_width=wnd.width();if(wnd_width<=1024){el.removeClass('t226__fixedTop');el.removeClass('t226__fixedBottom');el.removeClass('t226__floating');return('')}
el.css('max-width',col.width());if(col.height()<el.height()&&col.height()>0){col.height(el.height())}
var el_height=el.height();var col_top=col.offset().top;var col_width=col.width();var col_height=col.height();var col_bottom=col_top+col_height;var wnd_top=wnd.scrollTop();var wnd_bottom=wnd_top+wnd_height;if(wnd_top+el_height+50>=col_bottom){el.addClass('t226__fixedBottom');el.removeClass('t226__fixedTop');el.removeClass('t226__floating')}else if(wnd_top+50>col_top){el.addClass('t226__floating');el.removeClass('t226__fixedBottom');el.removeClass('t226__fixedTop')}else{el.addClass('t226__fixedTop');el.removeClass('t226__fixedBottom');el.removeClass('t226__floating')}}
function t412_init(recid){var rec=$('#rec'+recid);if(rec.find('a[href^="#order"]')){rec.find('a[href^="#order"]').on('click',function(e){var $linkelem=$(this);var $jspaybox=$('.js-payment-systembox');t412_setCoordinateToPaymentBox(e,$linkelem,$jspaybox);$jspaybox.css('margin-top','0');$jspaybox.css('margin-left','0');$(window).resize(function(){if($jspaybox.css('display')=='block'&&$linkelem){t412_setCoordinateToPaymentBox(e,$linkelem,$jspaybox)}})})}}
function t412_setCoordinateToPaymentBox(event,$linkelem,$jspaybox){var oldTopCoord=0;var newTopCoord=0;var offset=$linkelem.offset();var top=offset.top+$linkelem.parents('.t412__col').height()-$jspaybox.height();var left=offset.left+$linkelem.parents('.t412__col').width()/2-$jspaybox.width()/2;oldTopCoord=$jspaybox.css('top');$jspaybox.css('top',top+'px');$jspaybox.css('left',left+'px');newTopCoord=$jspaybox.css('top');if(parseInt(oldTopCoord)-parseInt(newTopCoord)==21){$jspaybox.css('top',(top+21)+'px')}}
function t412_unifyHeights(recid){var el=$("#rec"+recid);el.find('.t412__descr').css('height',"auto");$('#rec'+recid+' .t412 .t-container').each(function(){var highestBox2=0;$('.t412__descr',this).each(function(){if($(this).height()>highestBox2)highestBox2=$(this).height()});if($(window).width()>=960&&$(this).is(':visible')){$('.t412__descr',this).css('height',highestBox2)}else{$('.t412__descr',this).css('height',"auto")}});el.find('.t412__title').css('height',"auto");$('#rec'+recid+' .t412 .t-container').each(function(){var highestBox3=0;$('.t412__title',this).each(function(){if($(this).height()>highestBox3)highestBox3=$(this).height()});if($(window).width()>=960&&$(this).is(':visible')){$('.t412__title',this).css('height',highestBox3)}else{$('.t412__title',this).css('height',"auto")}});el.find('.t412__wrapper').css('height',"auto");$('#rec'+recid+' .t412 .t-container').each(function(){var highestBox=0;$('.t412__wrapper',this).each(function(){if($(this).height()>highestBox)highestBox=$(this).height()});if($(window).width()>=960&&$(this).is(':visible')){$('.t412__wrapper',this).css('height',highestBox)}else{$('.t412__wrapper',this).css('height',"auto")}})}
function t569_init(recid){var el=$('#rec'+recid);var line=el.find('.t569__line');var blocksnumber=el.find('.t569').attr('data-blocks-count');if(blocksnumber=='4'){var cirqlenumber=4}else{var cirqlenumber=8}
line.each(function(){var e=$(this).find('.t569__cirqle');for(i=0;i<cirqlenumber;i++){e.clone().insertAfter(e)}});line.css('max-width',el.find('.t569__col').width()-el.find('.t569__bgimg').outerWidth());$(window).on('resize',t_throttle(function(){line.css('max-width',el.find('.t569__col').width()-el.find('.t569__bgimg').outerWidth())}))}
function t670_init(recid){t670_imageHeight(recid);t670_show(recid);t670_hide(recid)}
function t670_show(recid){var el=$('#rec'+recid);var play=el.find('.t670__play');play.click(function(){if($(this).attr('data-slider-video-type')=='youtube'){var url=$(this).attr('data-slider-video-url');$(this).next().html("<iframe class=\"t670__iframe\" width=\"100%\" height=\"100%\" src=\"https://www.youtube.com/embed/"+url+"?autoplay=1\" frameborder=\"0\" webkitallowfullscreen mozallowfullscreen allowfullscreen allow=\"autoplay\"></iframe>")}
if($(this).attr('data-slider-video-type')=='vimeo'){var url=$(this).attr('data-slider-video-url');$(this).next().html("<iframe class=\"t670__iframe\" width=\"100%\" height=\"100%\" src=\"https://player.vimeo.com/video/"+url+"\" frameborder=\"0\" allow=\"autoplay; fullscreen\" allowfullscreen></iframe>")}
$(this).next().css('z-index','3')})}
function t670_hide(recid){var el=$('#rec'+recid);var body=el.find('.t670__frame');el.on('updateSlider',function(){body.html('').css('z-index','')})}
function t670_imageHeight(recid){var el=$('#rec'+recid);var image=el.find('.t670__separator');image.each(function(){var width=$(this).attr('data-slider-image-width');var height=$(this).attr('data-slider-image-height');var ratio=height/width;var padding=ratio*100;$(this).css('padding-bottom',padding+'%')})}